workspace(name = "minimal_isystem_example")

# Bazel will regard this as an external dependency (despite being a *local*
# repository). This will lead to header files from external_lib being included
# via -isystem instead of -I (which is what we are testing here).
local_repository(
    name = "external_lib",
    path = "third_party/my_lib",
)

# Since we created a WORKSPACE file, we manually include these as well. The
# other tests don't have this because they don't have a WORKSPACE file.
local_repository(
    name = "bazel_codechecker",
    path = "../../../",
)

load(
    "@bazel_codechecker//src:tools.bzl",
    "register_default_codechecker",
    "register_default_python_toolchain",
)

register_default_python_toolchain()

register_default_codechecker()
