# Copyright 2023 Ericsson AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Setup environment for redhat9'
description: 'Sets up analyzers, CodeChecker and Bazel for rhel9 CI runner'
runs:
  using: "composite"
  steps:
      - name: Set bazel version to 6.5.0
        run: echo "6.5.0" > .bazelversion
        shell: bash

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-codechecker

      - name: Install CodeChecker analyzers
        run: |
          dnf update -y && \
          dnf install -y \
            llvm-toolset \
            clang-tools-extra \
            wget \
            git \
            python3 \
            python3-pip \
            gcc \
            g++ \
            scl-utils \
        shell: bash

      - name: Install CodeChecker
        run: pip3 install codechecker
        shell: bash

      - name: Setup Bazel
        run: |
          VERSION=1.26.0; \
          wget "https://github.com/bazelbuild/bazelisk/releases/download/v$VERSION/bazelisk-linux-amd64" && \
          chmod +x bazelisk-linux-amd64 && \
          mv bazelisk-linux-amd64 /usr/local/bin/bazel && \
          USE_BAZEL_VERSION=6.5.0 bazel version
        shell: bash
