name: 'Setup environment for redhat9'
description: 'Sets up analyzers, CodeChecker and Bazel for rhel9 CI runner'
runs:
  using: "composite"
  steps:
      - name: Set bazel version to 6.5.0
        run: echo "6.5.0" > .bazelversion
        shell: bash

      - name: Install CodeChecker analyzers
        run: |
          dnf update -y && \
          dnf install -y \
            llvm-toolset \
            clang-tools-extra \
            wget \
            git \
            python3 \
            python3-pip \
            gcc \
            g++ \
            scl-utils \
        shell: bash

      - name: Install CodeChecker
        run: pip3 install codechecker
        shell: bash

      - name: Setup Bazel
        run: |
          VERSION=1.26.0; \
          wget "https://github.com/bazelbuild/bazelisk/releases/download/v$VERSION/bazelisk-linux-amd64" && \
          chmod +x bazelisk-linux-amd64 && \
          mv bazelisk-linux-amd64 /usr/local/bin/bazel && \
          USE_BAZEL_VERSION=6.5.0 bazel version
        shell: bash
