name: codechecker-bazel-tests

# Triggers the workflow on push or pull request events.
on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rules_test:
    name: Analysis
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set bazel version to 6.5.0
        run: echo "6.5.0" > .bazelversion

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install CodeChecker analyzers
        run: |
          sudo apt-get update --quiet
          sudo apt-get install --no-install-recommends \
            clang \
            clang-tools \
            clang-tidy

      - name: Install CodeChecker
        run: pip3 install codechecker

      - name: Print versions
        run: |
          bazel version
          CodeChecker version
          echo "[NOTE]: If you are debugging, its possible that " \
               "CodeChecker finds different analyzers when running in " \
               "bazel's sandbox environment!"
          CodeChecker analyzers

  unit_test:
    name: Unit Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set bazel version to 6.5.0
        run: echo "6.5.0" > .bazelversion

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install CodeChecker analyzers
        run: |
          sudo apt-get update --quiet
          sudo apt-get install --no-install-recommends \
            clang \
            clang-tools \
            clang-tidy

      - name: Install CodeChecker
        run: pip3 install codechecker

      - name: Print versions
        run: |
          bazel version
          CodeChecker version
          echo "[NOTE]: If you are debugging, its possible that " \
               "CodeChecker finds different analyzers when running in " \
               "bazel's sandbox environment!"
          CodeChecker analyzers

      - name: Run tests
        run: |
          cd test
          python3 test.py -vvv
