name: codechecker-bazel-tests

# Triggers the workflow on push or pull request events.
on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rules_test:
    name: Unit tests on ubuntu
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/platform_environment_setup/ubuntu

      - name: Print versions
        run: |
          bazel version
          CodeChecker version
          echo "[NOTE]: CodeChecker may find different analyzer binaries" \
               "when invoking directly, or in bazel's sandbox environment!" \
               "Be sure to double check during debugging."
          CodeChecker analyzers

      - name: Run tests
        run: |
          cd test
          python3 test.py -vvv

  rhel9_test:
    name: Unit tests on RHEL9
    runs-on: ubuntu-24.04
    container: redhat/ubi9:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/platform_environment_setup/rhel9

      - name: Print versions
        run: |
          bazel version
          CodeChecker version
          echo "[NOTE]: CodeChecker may find different analyzer binaries" \
               "when invoking directly, or in bazel's sandbox environment!" \
               "Be sure to double check during debugging."
          CodeChecker analyzers

      - name: Run tests
        run: |
          cd test
          python3 test.py -vvv
